### ISSUE TITLE
Problems using trm-client.  Error: Package includes objects without devclass.

### ISSUE THREAD

**Issue by EliezerRamCab** [RegestaItalia/trm-client#41]
Hi!

Thank you for creating this project. My colleagues and I find it very interesting and potentially useful for our work.

I have been playing around with this software and I'm encountering an error when attempting to install packages (including hello-world) using trm-client on my development server. This error occurs consistently across all packages I've tried to install.

This is the install command:
_PS C:\Users\Administrator> trm install hello-world
? Select connection type SAP Logon Connection
? Select connection XXX
? Logon Client XXX
? Logon User XXXXXXX
? Logon Password
✔ Connected to XXX as XXXXXXX.
ℹ TRM Public Registry - Alpha. Plans are currently disabled.
ℹ "hello-world" version latest -> 1.0.0 found in registry public
ℹ Package has 0 dependencies.
ℹ This is R3trans version 6.26 (release 754 - 01.08.24 - 14:07:06).
? Input name for package "Z T R M _ H E L L O W O R L D" ZTRM_HELLOWORLD
✖ Error: Package includes objects without devclass._

 Am I doing something wrong? 

Thank you for your assistance in resolving this problem. If you need additional information, please feel free to ask. 

Kind regards,
Eliezer,

**Comment by simonegaffurini** [comment]
Hi Eliezer, sorry for the late reply, I must have missed the notification.

You're doing everything correctly so I suspect it's an old bug fixed in the newer releases or something R3Trans releated.

What's your client version?
Doing `trm -cv` should give you nothing older than `3.1.6`.

If that's not the case, uninstall and reinstall trm like this:
- `npm uninstall trm-client -g`
- `npm install trm-client -g`

Let me know if it helps, otherwise I'll have a look into R3Trans 6.26 release 754.

**Comment by simonegaffurini** [comment]
I actually have a pc with R3trans 6.26 release 754 and found out it's a bug!
I'll try to get it fixed and reply when ready.
Thanks!

**Comment by simonegaffurini** [comment]
Version 1.4.0 of [node-r3trans](https://github.com/RegestaItalia/node-r3trans) was released and should fix issues with unicode releases.
@EliezerRamCab Please try forcing update of trm-client like this:

- `npm uninstall trm-client -g`
- `npm install trm-client -g`

and see if it fixes your issue.
Thanks

**Comment by EliezerRamCab** [comment]
Hi Simone!

It worked like a charm! thanks! 

I plan to keep experimenting with this and let you know if i have more issues or questions.

By the way, i had another problem. Probably the other one might have been overlooked too. It is the issue:
https://github.com/RegestaItalia/trm-core/issues/67

I would appreciate your feedback in this issue too.

Thanks again!
